// .NET-style number/bool formatters that match `XmlSerializer`'s output.
// Real-world `.bbm` files were generated by C# `XmlSerializer` over the
// years — every byte of the format mirrors that serialiser's defaults.
// We must emit the same shapes back.

/**
 * Format a finite number the way C#'s `Single.ToString()` /
 * `Double.ToString()` does in InvariantCulture, with default precision.
 *
 * Defaults:
 *   - Single → "G7" (7 significant digits)
 *   - Double → "G15" (15 significant digits)
 *
 * Both round-trip to "shortest decimal that uniquely identifies the value"
 * and strip trailing zeros — including the decimal point itself when the
 * value is integral. So `0.0 → "0"`, `1.5 → "1.5"`, `190.5 → "190.5"`.
 *
 * JS numbers are doubles, but the desktop's float fields are emitted at
 * G7 and real `.bbm` files reflect that. We default to G15 (lossless for
 * any JS number) but expose `precision` so the writer can match the
 * field-level choices observed in real files.
 *
 * Edge cases the C# format DOESN'T do:
 *   - "1." → C# emits "1", we must match
 *   - scientific notation: we follow the desktop writer (Qt 'g'): below
 *     1e-4 or at/above 10^precision, with .NET's upper-case exponent,
 *     e.g. "1.5E-05", "1.234568E+07"
 *   - "-0" → C# emits "0", JS toFixed/toPrecision may emit "-0"; coerce to 0
 */
export function formatNumber(n: number, precision: 'g7' | 'g15' = 'g15'): string {
  if (!Number.isFinite(n)) {
    throw new Error(`cannot format non-finite number: ${n}`);
  }
  const digits = precision === 'g7' ? 7 : 15;
  // Desktop holds g7 fields as `float` and formats the float
  // (XmlPrimitives.cpp formatFloat), so round to single precision first.
  if (precision === 'g7') n = Math.fround(n);
  // Normalise -0 → 0 so we never emit a leading minus on integral zero.
  if (Object.is(n, -0)) n = 0;
  if (n === 0) return '0';

  // Desktop formats with QString::number(v, 'g', digits)
  // (XmlPrimitives.cpp formatInvariantDouble), i.e. printf-%g rules:
  // scientific when the decimal exponent is < -4 or >= digits, trailing
  // zeros stripped, exponent signed and at least two digits, with the
  // upper-case E .NET writes ("1E-05", XmlPrimitives.cpp:18-22).
  // JS toPrecision switches at different pivots (< -6) and omits the
  // exponent padding, so build it from toExponential instead.
  const [mantissa, expStr] = n.toExponential(digits - 1).split('e') as [string, string];
  const exp = parseInt(expStr, 10);
  if (exp < -4 || exp >= digits) {
    const m = stripZeros(mantissa);
    const sign = exp < 0 ? '-' : '+';
    return `${m}E${sign}${String(Math.abs(exp)).padStart(2, '0')}`;
  }
  // Integral values within range print without a decimal point.
  if (Number.isInteger(n)) return n.toString();
  return stripZeros(n.toFixed(Math.max(0, digits - 1 - exp)));
}

/** ".25000" → ".25", "1.50" → "1.5", "1." → "1". */
function stripZeros(s: string): string {
  return s.includes('.') ? s.replace(/0+$/, '').replace(/\.$/, '') : s;
}

/**
 * Format an integer the way C#'s `Int32.ToString()` does:
 * decimal, no leading zeros, with a leading minus for negatives.
 *
 * We accept floats too because JS doesn't have a separate int type;
 * `Math.trunc` first to avoid emitting "1.0" or similar.
 */
export function formatInt(n: number): string {
  if (!Number.isFinite(n)) throw new Error(`not a finite int: ${n}`);
  return Math.trunc(n).toString();
}

const DECIMAL_FLOAT = /^[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?$/;
const DECIMAL_INT = /^[+-]?\d+$/;

/**
 * Read a float field like desktop `readFloatElement` (QString::toFloat,
 * XmlPrimitives.cpp:47-57): plain decimal or scientific notation only;
 * anything else — empty, `abc`, `NaN`, `-INF`, `12abc`, or a value that
 * overflows to infinity like `1e999` — reads as 0, so a damaged file
 * still loads and can be saved again.
 */
export function parseXmlFloat(raw: string | undefined): number {
  const s = (raw ?? '').trim();
  if (!DECIMAL_FLOAT.test(s)) return 0;
  const v = Number(s);
  return Number.isFinite(v) ? v : 0;
}

/** Read an int field like desktop `readIntElement` (QString::toInt): anything but a plain integer reads as 0. */
export function parseXmlInt(raw: string | undefined): number {
  const s = (raw ?? '').trim();
  if (!DECIMAL_INT.test(s)) return 0;
  const v = Number(s);
  return Number.isSafeInteger(v) && v >= -2147483648 && v <= 2147483647 ? v : 0;
}

/** `true` / `false` lowercase, matching `Boolean.ToString().ToLower()`. */
export function formatBool(b: boolean): 'true' | 'false' {
  return b ? 'true' : 'false';
}

/** Inverse of `formatBool` — accepts any case for forward compatibility. */
export function parseBool(raw: string): boolean {
  const v = raw.trim().toLowerCase();
  if (v === 'true') return true;
  if (v === 'false') return false;
  throw new Error(`not a boolean: ${raw}`);
}
