// .NET-style number/bool formatters that match `XmlSerializer`'s output.
// Real-world `.bbm` files were generated by C# `XmlSerializer` over the
// years — every byte of the format mirrors that serialiser's defaults.
// We must emit the same shapes back.

/**
 * Format a finite number the way C#'s `Single.ToString()` /
 * `Double.ToString()` does in InvariantCulture, with default precision.
 *
 * Defaults:
 *   - Single → "G7" (7 significant digits)
 *   - Double → "G15" (15 significant digits)
 *
 * Both round-trip to "shortest decimal that uniquely identifies the value"
 * and strip trailing zeros — including the decimal point itself when the
 * value is integral. So `0.0 → "0"`, `1.5 → "1.5"`, `190.5 → "190.5"`.
 *
 * JS numbers are doubles, but the desktop's float fields are emitted at
 * G7 and real `.bbm` files reflect that. We default to G15 (lossless for
 * any JS number) but expose `precision` so the writer can match the
 * field-level choices observed in real files.
 *
 * Edge cases the C# format DOESN'T do:
 *   - "1." → C# emits "1", we must match
 *   - "1e+02" scientific → only kicks in past G's threshold
 *   - "-0" → C# emits "0", JS toFixed/toPrecision may emit "-0"; coerce to 0
 */
export function formatNumber(n: number, precision: 'g7' | 'g15' = 'g15'): string {
  if (!Number.isFinite(n)) {
    throw new Error(`cannot format non-finite number: ${n}`);
  }
  // Normalise -0 → 0 so we never emit a leading minus on integral zero.
  if (Object.is(n, -0)) n = 0;

  // C# integer-fast-path: integral values print without a decimal point.
  if (Number.isInteger(n)) return n.toString();

  const digits = precision === 'g7' ? 7 : 15;
  // toPrecision uses N sig digits and may switch to exponential at the
  // edges. C#'s G format uses the SAME pivot (~10^-5 lower, ~10^N upper),
  // so the scientific edge cases are mostly aligned. Real `.bbm` files
  // have no values in the scientific range, so this is good enough for v1.
  let s = n.toPrecision(digits);

  // Strip trailing zeros after the decimal point, then a trailing dot if
  // any. ".25000" → ".25", "1.50" → "1.5", "1." → "1".
  if (s.includes('.') && !s.includes('e') && !s.includes('E')) {
    s = s.replace(/0+$/, '').replace(/\.$/, '');
  }
  return s;
}

/**
 * Format an integer the way C#'s `Int32.ToString()` does:
 * decimal, no leading zeros, with a leading minus for negatives.
 *
 * We accept floats too because JS doesn't have a separate int type;
 * `Math.trunc` first to avoid emitting "1.0" or similar.
 */
export function formatInt(n: number): string {
  if (!Number.isFinite(n)) throw new Error(`not a finite int: ${n}`);
  return Math.trunc(n).toString();
}

/** `true` / `false` lowercase, matching `Boolean.ToString().ToLower()`. */
export function formatBool(b: boolean): 'true' | 'false' {
  return b ? 'true' : 'false';
}

/** Inverse of `formatBool` — accepts any case for forward compatibility. */
export function parseBool(raw: string): boolean {
  const v = raw.trim().toLowerCase();
  if (v === 'true') return true;
  if (v === 'false') return false;
  throw new Error(`not a boolean: ${raw}`);
}
