// LDraw color names (English) from BlueBrick's ColorTable.xml, as desktop
// parts::colorName uses for the part list (generated from
// src/parts/data/ColorTable.xml; 77 colors).

const COLOR_NAMES: Readonly<Record<number, string>> = {
  0: 'Black',
  1: 'Blue',
  2: 'Green',
  3: 'Teal',
  4: 'Red',
  5: 'Dark Pink',
  6: 'Brown',
  7: 'Gray',
  8: 'Dark Gray',
  9: 'Light Blue',
  10: 'Bright Green',
  11: 'Turquoise',
  12: 'Light Red',
  13: 'Pink',
  14: 'Yellow',
  15: 'White',
  17: 'Light Green',
  18: 'Light Yellow',
  19: 'Tan',
  20: 'Light Violet',
  21: 'Phosphor White',
  22: 'Violet',
  23: 'Violet Blue',
  25: 'Orange',
  26: 'Magenta',
  27: 'Lime',
  28: 'Dark Tan',
  29: 'Light Purple',
  33: 'Trans Blue',
  34: 'Trans Green',
  36: 'Trans Red',
  37: 'Trans Violet',
  40: 'Trans Gray',
  41: 'Trans Light Cyan',
  42: 'Trans Flu Lime',
  45: 'Trans Pink',
  46: 'Trans Yellow',
  47: 'Clear',
  57: 'Trans Flu Orange',
  69: 'Bright Purple',
  70: 'Reddish Brown',
  71: 'Stone Gray',
  72: 'Dark Stone Gray',
  73: 'Medium Blue',
  74: 'Medium Green',
  77: 'Paradisa Pink',
  78: 'Light Flesh',
  79: 'Translucent White',
  85: 'Medium Lilac',
  86: 'Dark Flesh',
  89: 'Royal Blue',
  92: 'Flesh',
  134: 'Pearl Copper',
  135: 'Pearl Gray',
  137: 'Pearl Sand Blue',
  142: 'Pearl Gold',
  151: 'Light Stone',
  256: 'Rubber Black',
  272: 'Dark Blue',
  273: 'Rubber Blue',
  288: 'Dark Green',
  313: 'Maersk Blue',
  320: 'Dark red',
  324: 'Rubber red',
  334: 'Chrome Gold',
  335: 'Sand Red',
  366: 'Earth Orange',
  373: 'Sand Violet',
  375: 'Rubber Gray',
  378: 'Sand Green',
  379: 'Sand Blue',
  383: 'Chrome Silver',
  462: 'Light Orange',
  484: 'Dark Orange',
  494: 'Electric Contact',
  503: 'Light Gray',
  511: 'Rubber White',
};

/** Name of LDraw color `code` ("0" → "Black"); empty for an unknown or non-numeric code. */
export function colorName(code: string): string {
  if (!/^\d+$/.test(code.trim())) return '';
  return COLOR_NAMES[Number(code)] ?? '';
}
