export type { Catalog, ConnectionPoint, PartKind, PartMetadata, SubPart } from './types.js';
export { parsePartXml, type ParseInput } from './parse.js';
export { scanCatalog, statRoot, type ScanResult } from './scan.js';
export { rebuildConnectivity, type RebuildConnectivityResult } from './connectivity.js';
export { footprint, imageOffset, type Footprint, type FootprintPart } from './footprint.js';
export { imageSize, type ImageSize } from './imageSize.js';
export { effectivePxPerStud, spriteExtensionsFor, VANILLA_PX_PER_STUD, xmlForGifSprite } from './spriteScale.js';
export { connectionHingeAngle, FlexMove, type FlexSnapTarget, type FlexState } from './flexMove.js';
export type { FourDBrixRemap, FourDBrixType, LDrawRemap, TrackDesignerPort, TrackDesignerRemap } from './types.js';
export { MapLibrary, newBrickLayer, newGridLayer, newMap, type MapReadResult } from './mapformats/library.js';
export { readFourDBrixMap, writeFourDBrixMap, type FourDBrixWriteOptions } from './mapformats/fourDBrix.js';
export { partForTrackDesignerId, readTrackDesignerMap, writeTrackDesignerMap } from './mapformats/trackDesigner.js';
export { readLDrawMap, writeLDrawMap, type LDrawReadOptions } from './mapformats/ldraw.js';
